### PR TITLE
just made the header sticky

### PR DESCRIPTION
**Pull request by Nathanim1919**
while scrolling the add community/group button and social links stay at the top.

### CODE REVIEW

**Comment by dagmawibabi** [comment]
This's really cool feature but it doesn't stay stuck when the list part join. Can you make it stick for the whole time.

**Comment by dagmawibabi** [comment]
@Nathanim1919 you should make it stick the whole time a person scrolls.

**Comment by Nathanim1919** [comment]
yeap, It did now

**Comment by dagmawibabi** [comment]
image

It needs a suitable background. @Nathanim1919

**Pull request closed without merging**
